sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine=1.10.3-0~trusty

install:
  - docker build -t tylerreddy/steric-conflict-resolution docker_build/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
     docker push tylerreddy/steric-conflict-resolution;
    fi
