sudo: required
language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine=1.10.3-0~trusty

install:
  - docker build -t tylerreddy/steric-conflict-resolution docker_build/

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker run -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" tylerreddy/steric-conflict-resolution /bin/sh -c "cd /steric_conflict_resolution; nosetests --verbosity=3 --with-coverage --cover-package run_steric_resolution generate_mdp tests.py 2>&1 | tee nose.log; coveralls; tail -1 nose.log | grep -q OK";
    else 
     docker run tylerreddy/steric-conflict-resolution /bin/sh -c "cd /steric_conflict_resolution; nosetests --verbosity=3 --with-coverage --cover-package run_steric_resolution tests.py 2>&1 | tee nose.log; tail -1 nose.log | grep -q OK";
    fi 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
     docker push tylerreddy/steric-conflict-resolution;
    fi
